### ISSUE TITLE
Issue with savePath in File

### ISSUE THREAD

**Issue by soma-social** [SlabPHP/session-manager#1]
Hello, 

I've decided to use this in one of my projects and when I've setup the Session File as per your example:

```
$handler = new \Slab\Session\Handlers\File();

$handler->setSavePath(ini_get('session.save_path'));
```
I was receiving a PHP warning:

```
Warning: mkdir(): No such file or directory in [private...]\vendor\slabphp\session-manager\src\Handlers\File.php on line 45
```
that's where **mkdir** function is, and that's because in your Drive class you call open with the first param "false".

The problem is in the **Handlers\File.php** file in the **open** method, I've created my own Session File Handler class that extends your **Handlers\File.php** class in order to fix this:

```
	public function open( $savePath, $sessionName )
	{
		if ( empty( $savePath ) ) {
			if ( empty( $this->savePath ) ) {
				$this->setSavePath( static::DEFAULT_SAVE_PATH );
			}
			else {
				$this->setSavePath( $this->savePath );
			}
		}
		else {
			$this->setSavePath( $savePath );
		}

		return true;
	}
```

PS:
On windows, there is no "/tmp/session". At least, not on mine.

Hope this helps

**Comment by ericsalerno** [comment]
Great catch! Updating this now in 0.1.11. Feel free to submit pull requests!

**Comment by soma-social** [comment]
Thank you! :)
